require 'uri'
require 'net/http'
require 'nokogiri'

require 'page_weight/html_document'
require 'page_weight/http'
require 'page_weight/page_weight'
require 'page_weight/parser'
require 'page_weight/reporter'
require 'page_weight/url'